[versions]
vavr = "0.11.0"
logback = "1.5.25"
junitBom = "6.0.2"
awaitility = "4.3.0"
jackson = "2.21.0"
kafka = "4.1.1"
jdbi = "3.51.0"

[libraries]
# Libraries
vavr = { group = "io.vavr", name = "vavr", version.ref = "vavr" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }

jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version = "2.21" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-datatype = {group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version.ref = "jackson" }
jackson-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
kafka-client = {group = "org.apache.kafka", name = "kafka-clients", version.ref= "kafka"}

jdbi-core = {group = "org.jdbi", name = "jdbi3-core", version.ref= "jdbi"}
jdbi-sqlobject = {group = "org.jdbi", name = "jdbi3-sqlobject", version.ref= "jdbi"}
jdbi-stringtemplate4 = {group = "org.jdbi", name = "jdbi3-stringtemplate4", version.ref= "jdbi"}

testcontainers-kafka = {group = "org.testcontainers", name = "kafka", version = "1.21.3"}

mockito = { group = "org.mockito", name = "mockito-core", version = "5.21.0" }

# Platforms (BOMs)
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }

[bundles]
jdbi = ["jdbi-core", "jdbi-sqlobject", "jdbi-stringtemplate4"]
jackson = ["jackson-annotations", "jackson-databind", "jackson-datatype", "jackson-jsr310"]
logback = ["logback-core", "logback-classic"]
junit = ["junit-jupiter"]
